language: sass
dist: trusty

addons:
  sonarcloud:
    organization: "adshares-github"
    token:
      secure: "PqdGbhR8VAU+qeonCeEMBf8IgiqV2FVKTgEOIt/7JnQjd0ybtcgZNIxkJRbdnSRF0WRbCzuH8W6gSeemEsD9QaV0sORcD5DNLOj0Xld9cPmdvyZ9dyl5VA7w0461OUlfNbeMulGdbIOYTavpm3kpVStluebFwCkk9pEkGBYIFx4xkp9TmhGzwmvZW01BbuK4fJatvLXzewpeWVxQL0HM+d6QfqOMHrnDGc4bvf3DYrMSQGPB4f5R3NvscconT3VRxxpIJSe4nc6wzpNZNUsbFGLF8hSAEbfE+4aDUKaqgJGJlLMwjU8+LJVeLigYse2qdjs9HGMlfs61CsYHguLVpS64yd+w8C+P2CsVEfSjRk8TAFJEu3F3Me/OmnPSW0JwawI4teXAfia9+Ml7xDjnU91uy2gQ9uuM5WSLQe/fU+htVQANb0sFxRMrfHYoRqUyKpWvLcUVep1xmxkrTfX4c3gt3J05L8TU11H5NMa15jKN7kF2MztDq+Oag0zj9UszV3FGu15XEl0CYloCNN/ciFgpjvUh8nR2Mxnxk1ggw06JLlYSM4N0tOwQYnh6GKnzWJXSE1fAVtuNVpxQ6f9v3dlAjYJnelPrBFBHHJ+0c4baodTp5uzcQFNvJ3Mrble2endP0KQAvdLrY65e4HOmL3BfcMnZ0HR6pkSQqZ0LD6M="
    github_token:
      secure: "TNngO0eZnSUJaYiDI+7LoDb6fnGGP/W0C6SmzxNI8AoBUQ7BkZDtC8AyrkzLqFkM7QNN+cuMEpeYecW6mjcOplSuhFc40uy/JdrlneI5RIGSJJ6HXXVHLdv0TR34sXk7vW1nbYgKlN0aOFG8XBYUoTymRs89bEGxzMgaHvh18LIuaSU5JCXBi1JKDfi3p7Otsqa48rla0F+q8Az6DxuexHCsI63Dx82QrDSd5HnxYbKlRnLPLKhWVdUvWYrOOo+Bww1sKcPsnGDBfwtLV4OKDLs2DX7sVdMiqjkz/hrf/5h6UlrrWlruC9FqgGH231Gb2si0uK6DbGjPiM3DxyjP01wgAgatGLouzNksuTYBjdV154CYpHbbkFHReXG/x6DEse4VQpvpep/n4bCoW1urdskYGq8gzHmwcQytBnO0BVUlz6A++1hpDO93CTZAzaV5Ee3zfyE4Hw+LIA8GPvkz9QCXQwUUuIJC2WCu4FnjK1elbTVgUJsCm9VuVWitAU6LtXow7LC/5nn2nlNsqCRz3oRAs/5z6lZgPGMkpBC9PFNf903GvAangT4LAr/Kp0EXWg5D1AmSl+YrpxviskaKrqWf3ZvDn9OpxL/KWSWtVV93S9MaEq9pMOINaGChMHdEPhxE/ixCPO11zk/HtKa4Mni7/ac9EXae49o2fojP9bc="

before_install:
  - gem install sass

script:
  - ./test/travis.rb
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

notifications:
  email: false
  slack:
    rooms:
      secure: "g+5Ckhxa5hoySkddHeY1duiLJzvsmZ3plDW4dKenCv1T/GWAtrt53Pqg8nZZ/KzrAF1W6CuJQ3TRa32Af1gnxNDG9NindRofZJqD+vDklwLGJ8fv8SKabIzjkslhWLMrTlQPZEggDaxGocKMYXt8Ph0C8RBHuuwpg7mtHlwXg40zB4+EI3Wm7HytbBPrNjLtNnEzuF+J20EKaMsqorS53bXt3RDlxMSHL+LH3QEHXa8p11TeIzJguBHxeKcms9t5MFILWnTt6f0yVFWfoFC8vh/Ww6/pEKVY8cYAJ9XfEyktF+RW9LLGUZGaDoSXa3bdZMZV9JnpWgk8s8WnJ89pi3GHaaXDFZnuwpLmajsE/YIkhWshwALjLFoTwR70hj22Ub8FTaRi/Gj7vtS0w0c2J0cyYRU2g+zj6SYLMdvG0sdU3j4aeGCfR5drVxpHyMeNk/GdJxyqAW0SloUvnd1v1auwzeNjG/wQjUKsN2zEfp3IT8Fbbe1VV0vSvHU4g2jnOvQYLQphJUvI+M0lm0n3LF11lzPDSZ7iWMnhjnIhJz38L9xP8WHiqwkyhQlef9DYdMZ6QOuwYNc28JfHhee5mty+Nz8ap/0veGcCMEIBGat9tBMzbFnI+dRi7hL9eNRlEuSQOo35EbMeh1ex57xlEYSGn4PM+lgEJRjwB9HFcrY="
    on_success: change
    on_failure: always
